name: Process Note Proposals
on:
  issues:
    types: [opened, edited]
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  process-note-proposal:
    if: contains(github.event.issue.labels.*.name, 'note-proposal')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install beautifulsoup4 tqdm ruamel.yaml
      - name: Parse issue and create branch
        id: parse_issue
        run: |
          echo "Parsing issue..."
          ISSUE_NUMBER=$(echo "${{ github.event.issue.number }}")
          BRANCH_NAME="note-proposal-${ISSUE_NUMBER}"
          ISSUE_DATE=$(echo "${{ github.event.issue.created_at }}" | cut -d'T' -f1)
          echo "##[set-output name=branch_name;]${BRANCH_NAME}"
          echo "##[set-output name=issue_date;]${ISSUE_DATE}"
          
          # Create/reset feature branch from master
          git checkout -B ${BRANCH_NAME}
      - name: Add note to YAML file
        run: |
          echo "Adding note to YAML file..."
          python .github/workflow_scripts/add_note.py "${{ github.event_path }}"
      - name: Generate preview
        id: generate_preview
        run: |
          echo "Generating preview..."
          # Extract paragraph number from the issue
          PARAGRAPH_NUMBER=$(python -c "
          import json, sys
          event = json.load(open('${{ github.event_path }}'))
          lines = event['issue']['body'].split('\n')
          for line in lines:
              line = line.strip()
              if line.startswith('### ') and 'Paragraph Number' in line:
                  continue
              elif line and line.isdigit():
                  print(line)
                  break
          ")
          echo "Paragraph number: $PARAGRAPH_NUMBER"
          python .github/workflow_scripts/generate_preview.py "$PARAGRAPH_NUMBER" "${{ github.event.issue.number }}"
          echo "##[set-output name=paragraph_number;]${PARAGRAPH_NUMBER}"
      - name: Upload preview to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: preview/
          server-dir: preview/
      - name: Commit and push changes
        run: |
          echo "Committing changes..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add note from issue #${{ github.event.issue.number }}"
            echo "Force pushing changes..."
            git push -f origin ${{ steps.parse_issue.outputs.branch_name }}
          fi
      - name: Comment on issue with PR link
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.issue.number }}")
          BRANCH_NAME="note-proposal-${ISSUE_NUMBER}"
          PR_LINK="https://github.com/${{ github.repository }}/compare/${BRANCH_NAME}?expand=1"
          PREVIEW_LINK="https://hpmor.info/preview/${ISSUE_NUMBER}.html"
          COMMENT_BODY="Your note proposal has been processed!

          Preview the note: ${PREVIEW_LINK}

          Next steps:
          - You can edit the text of your issue to update the note (the preview will be regenerated automatically)
          - Maintainers can create a pull request using this link: ${PR_LINK}"
          gh api -X POST /repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments -f body="${COMMENT_BODY}"