name: Build and upload website
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build website
        run: |
          pip install beautifulsoup4 tqdm ruamel.yaml
          mkdir html && mv reddit-fetch html/reddit-fetch
          python build.py
      - name: Upload files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: html/